path: "/content/training_data" #"/content/gdrive/My Drive/spacecraft_detection_model/data"
train: images/train
val: images/val
test: images/test

nc: 15
names:
    0: 2
    1: 3
    2: 5
    3: 6
    4: 11
    5: 13
    6: 14
    7: 18
    8: 19
    9: 20
    10: 22
    11: 24
    12: 25
    13: 28
    14: 30
